engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 28
  fixme:
    enabled: true
    config:
      strings:
      - BUG
      - DEPRECATED
      - FIXME
      - HACK
      - IMPROVE
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
      ignore_warnings: false
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,design,naming,unusedcode"
ratings:
  paths:
  - "**.php"
exclude_paths:
- .**
- apigen.neon
- composer.json
- composer.lock
- LICENSE.txt
- phpunit.xml
- README.md
- docs/**/*
- mocks/**/*
- tests/**/*
- tmp/**/*
- vendors/**/*
