language: php

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  matrix:
    - HACK=0

matrix:
  include:
    - php: hhvm-nightly
      env: HACK=1
  allow_failures:
    - php: nightly

before_script: "if [ \"$HACK\" = \"1\" ]; then hhvm -vEval.EnableHipHopSyntax=true;"
script: phpunit
