language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
      env: HHVMPHP7="yes"
  allow_failures:
    - php: nightly

before_script:
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

script:
  - phpunit

branches:
  only:
    - develop
    - master
