language: php

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

sudo: required

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then hhvm -v Eval.EnableHipHopSyntax=true; fi'

script:
  - phpunit

branches:
  only:
    - develop
    - master
