language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm-stable
      env: PHP7MODE="yes"
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: hhvm-stable
    - php: nightly
  fast_finish: true

before_install:
  - if [[ $PHP7MODE == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
  - if [[ $(phpenv version-name) == '7.0' ]]; then composer require satooshi/php-coveralls:^1.0 -n; fi
  - if [[ $(phpenv version-name) != '7.0' ]]; then composer install -n; fi

before_script:
  - if [[ $(phpenv version-name) == '7.0' ]]; then mkdir -p tmp/logs; fi

script:
  - if [[ $(phpenv version-name) == '7.0' ]]; then vendor/bin/phpunit --coverage-clover tmp/logs/clover.xml; fi
  - if [[ $(phpenv version-name) != '7.0' ]]; then vendor/bin/phpunit; fi

after_script:
  - if [[ $(phpenv version-name) == '7.0' ]]; then vendor/bin/coveralls -v; fi

branches:
  only:
    - master

git:
  depth: 5

notifications:
  email: false
