language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm-stable
      env: PHP7MODE="yes"
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

before_script:
  - if [[ $PHP7MODE == "yes" ]]; then
      echo hhvm.php7.all=1 >> /etc/hhvm/php.ini;
    fi

script:
  - phpunit

branches:
  only:
    - master

git:
  depth: 5

notifications:
  email: false
